name: 03 - Actions 1.0

on:
  push:
    branches:
      - "feature/**" # precisa ser lista, não string simples

jobs:
  checkout_java_docker:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório
      - name: Git Checkout
        uses: actions/checkout@v4

      # Configura o Java 21 (Temurin)
      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # Constrói a imagem Docker localmente (sem push)
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false

      # Executa alguns comandos simples
      - name: Executar scripts
        run: |
          git branch
          java --version
          mvn clean package
